all:
  children:
    esxi:
      hosts:
        # esxi01:
        #   ansible_host: 10.10.40.21
        esxi02:
          ansible_host: 10.10.99.22
        esxi03:
          ansible_host: 10.10.99.23
